- hosts: mons
  gather_facts: false
  become: True
  pre_tasks:
    - name: set ceph monitor install 'In Progress'
      run_once: true
      set_stats:
        data:
          installer_phase_ceph_mon:
            status: "In Progress"
            start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
  roles:
    - ceph-defaults
    - ceph-common
    - ceph-config
    - ceph-mon
  post_tasks:
    - name: set ceph monitor install 'Complete'
      run_once: true
      set_stats:
        data:
          installer_phase_ceph_mon:
            status: "Completed"
            start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
