---
- hosts: all
  gather_facts: False
  become: yes
  
  task:
  - name: Restart server
    become: yes
    shell: sleep 2 && /sbin/shutdown -r now "Ansible system package upgraded"
    async: 1
    poll: 0
